mongodb:
  max:
    pool:
      size: 300

spring:
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: mongo
      port: 27017
      password: root
      username: root
    solr:
      host: http://127.0.0.1:8983/solr
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
    application:
      name: Goreit


#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true


server:
  port: 8080

#ribbon:
#  http:
#    client:
#      enabled: true

pricing:
  commission: 0.02
  default:
    balance: 100
    coins: 200
  coins:
    multipler: 5
    divider: 10
